version: '3.8'

services:

  mariadb:
    build: requirements/mariadb
    image: mariadb:idonado
    container_name: mariadb
    init: true
    environment:
      - DATABASE_WP
      - WP_DB_ROOT_PASSWORD
      - WP_DB_ADMIN_USER
      - WP_DB_ADMIN_PASSWORD
    networks:
      - app_default
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  nginx:
    build: requirements/nginx
    image: nginx:idonado
    container_name: nginx
    init: true
    depends_on:
      - wordpress
    networks:
      - app_default
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always

  wordpress:
    build: requirements/wordpress
    image: wordpress:idonado
    container_name: wordpress
    init: true
    environment:
      - WP_DB_ADMIN_USER
      - WP_DB_ADMIN_PASSWORD
      - DATABASE_WP
    depends_on:
      - mariadb
    networks:
      - app_default
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    restart: always

volumes:

  mariadb:
    name: mariadb_volume
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/mariadb
  wordpress:
    name: wordpress_volume
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress

networks:

  app_default:
    driver: bridge